name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install dependencies of poetry
      reun: |
        pip install poetry
        poetry install

    - name: Check Docker Compose
      run: |
        docker-compose config

    - name: Check if the containers are running
      run: |
        docker-compose ps
        if [ $? -ne 0 ]; then exit 1; fi

    - name: Check poetry build
      run: |
        poetry build

    - name: Run tests
      run: |
        pytest /testes/parser
        pytest /testes/data_pipeline/feature_engineering

    - name: Build Sphinx documentation
      run: |
        cd docs
        make html
        